### ISSUE TITLE
Aws credentials for path `/aws/sts/:name` and method `POST`

### ISSUE THREAD

**Issue by dprevost-LMI** [shahradelahi/node-vault#29]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

I need to use the sts path (`/aws/sts/:name`) to generate aws credentials like [documented here](https://developer.hashicorp.com/vault/api-docs/secret/aws#generate-credentials).

However, the code covers only the cred path (`/aws/creds/:name`)

Could it be possible to provide that?

I'm in the process of opening a PR, and I thought I could provide the below since I'm not sure how to tweak the current `credentials` to properly pass `method: 'POST ',` when using `/sts` over `/creds`

```
    /**
   * Generate credentials for the path `/aws/sts/:name`
   *
   * @link https://developer.hashicorp.com/vault/api-docs/secret/aws#generate-credentials
   */
    get stsCredentials() {
      return generateCommand({
        method: 'POST',
        path: '/aws/sts/{{name}}',
        client: this.client,
        schema: {
          path: z.object({
            name: z.string(),
            isSTS: z.boolean().optional()
          }),
          searchParams: z.object({
            role_arn: z.string().optional(),
            role_session_name: z.string().optional(),
            ttl: z.string().optional(),
            mfa_code: z.string().optional()
          }),
          response: z.any()
        }
      });
    }
```

### What type of pull request would this be?

See https://github.com/shahradelahi/node-vault/pull/30

**Comment by shahradelahi** [comment]
Closed by #30

**Comment by shahradelahi** [comment]
Hello @dprevost-LMI,

Did you try the new release? Today, when I reviewed your code again, I've seen issues. I do not own an AWS account to verify the problem. Can you let me know if the `stsCredentials` method returns with a success status?

By the way, thanks for your contribution.

**Comment by dprevost-LMI** [comment]
It works super well on my side. THe only thing I forgot in PR was to remove `isSTS`

**Comment by dprevost-LMI** [comment]
After seeing [this](https://github.com/shahradelahi/node-vault/pull/30#discussion_r1615130104) yes, there might be some cases I did not encounter yet since I was using only the below:
```
    const { data } = await vaultClient.aws.stsCredentials({
      name: role,
      ttl,
    });
```

Do you want me to open a new PR to fix the problem related to `searchParams`?

**Comment by dprevost-LMI** [comment]
😮 Probably my ttl does not work lol

**Comment by shahradelahi** [comment]
I already created a patch for it, but it would be great if you double-check and confirm that `ttl` is not being applied to the creds.

**Comment by dprevost-LMI** [comment]
I confirm the problem. It should have been 10h but I see only 899 sec
```
Body { name: 'redacted-live', ttl: '10h' }
AWS credentials generated {
  request_id: 'd3f324ff-efa6-4266-3a0d-redacted',
  lease_id: 'aws/sts/redacted-live/redacted',
  renewable: false,
  lease_duration: 900,
  data: {
    access_key: 'redacted',
    arn: 'arn:aws:sts::redacted:assumed-role/vault-sts-redacted-live/vault-oidc-redacted-m24R',
    secret_key: 'redacted',
    security_token: 'redacted',
    ttl: 899
  },
  wrap_info: null,
  warnings: null,
  auth: null
}
```
Using curl with proper ttl data as POST body, the returned ttl is `"ttl":35999`
